version: '3.7'
#định nghĩa các file image của docker compose mà mình muốn pull về
services: 
    #tên service(đặt tên gì cũng được)
    elasticsearch:
        #chỉ định file image muốn pull về
        #image: ten_image:version
        image: elasticsearch:8.3.3
        #tên của container docker
        container_name: elasticsearch
        #ánh xạ ổ đĩa docker đến ổ đĩa của hệ thống
        #đường dẫn máy:đường dẫn docker
        volumes:
            - ./elastic_data:/usr/share/elasticsearch/data
        ports:
           - 9200:9200
           - 9300:9300
        #nơi định các biến môi trường
        environment:
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            discovery.type: single-node
            ELASTIC_PASSWORD: "admin123"
            xpack.security.enabled: "false" 
        #network đang sử dụng là gì     
        networks:
            - elk

    kibana:
        image: kibana:8.3.3
        container_name: kibana
        ports:
            - 5601:5601
        environment:
        #http://ten_container:ten_port của elasticsearch
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        #username của elasticsearch   
            ELASTICSEARCH_USERNAME: kibana_system
        #password của kibana_system sau khi đổi password trên postman(localhost:9200/_security/user/kibana_system/_password)
            ELASTICSEARCH_PASSWORD: admin123
        depends_on:
            - elasticsearch
        networks:
            - elk
    
    logstash:
        image: logstash:8.3.3
        container_name: logstash
        command: logstash -f /usr/share/logstash/pipeline/logstash.conf
        ports:
            - 9600:9600
            - 5044:5044
        volumes:
            - ./logstash/logstash.yml:/usr/share/logstash/logstash.yml:ro,z
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
            - ./logs:/usr/share/logstash/logs:ro,z
        environment:
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        depends_on:
            - elasticsearch
        networks:
            - elk
    
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672     #port: producer đẩy data lên rabbitmq
            - 15672:15672   #port: truy cập giao diện web của rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "admin123"
        depends_on:
            - logstash      #vì lấy data và đẩy về logstash
        #do k cần file config nên k cần volumes
        networks:
            - elk

#định nghĩa lại volumes bên trên 
volumes:
    setup:
    elastic_data:

#3 cục service (elasticsearch, logtask, kibana) liên lạc với nhau qua cùng ip
networks:
    elk:
    #bridge: tạo cầu nối để 3 cục service elk tương tác qua lại
        driver: bridge


#cd [đường dẫn folder CentralLog]
#để start service chỉ định docker compose : docker-compose ten_service
#để start all service : docker-compose up
#để kiểm tra có server nào đang hoạt động : docker ps


#nội dung file logstash.conf
    #input {
        #định nghĩa những file log cần thu thập nội dung
    #     file {
    #         path => "/usr/share/logstash/logs/cineflix_api.log"
    #         sincedb_path => "/dev/null"
    #         start_position => "beginning"
    #     }
    # }

    # output {
    #     #nơi sẽ đẩy nội dung file log
    #     elasticsearch {
    #         hosts => ["elasticsearch:9200"] 
    #         index => "cineflix_api"
    #     }
    # }

#nội dung file logstash.yml
    # http.host: "0.0.0.0"
